### ISSUE TITLE
Incorrect assumptions about C data types

### ISSUE THREAD

**Issue by michael-platzer** [tacle/tacle-bench#16]
Some of the programs make assumptions about the default sign or width of C data types that are not mandated by the standard.

Two incorrect expectations that I encountered are the assumption that the type `char` is always signed and that the type `long` has a width of 64 bit. The C standard allows the type `char` to be either signed or unsigned and the type `long` has only a minimum width of 32 bits (the exact requirement is that it must be able to hold values ranging from -2147483647 to 2147483647 if signed and values up to 4294967295 if unsigned).

Both of these assumptions are wrong on 32-bit RISC-V, where the type `char` is unsigned by default and the type `long` is only 32 bits wide (as on most 32-bit architectures), see section 18.1 of the [RISC-V Calling Conventions](https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf). As a consequence, all the programs that rely on either one of these assumptions fail on 32-bit RISC-V.

I found 3 programs that are affected by this (though there could be more): `bench/sequential/h264_dec` assumes that `char` is signed; `bench/sequential/adpcm_enc` and `bench/sequential/ammunition` assume that `long` is 64 bits wide (or at least wider than 32 bits). The problem can be reproduced on other architectures than RISC-V by forcing GCC to assume that `char` is unsigned and replacing all `long` by `int32_t` (and `unsigned long` by `uint32_t`) and including the header `stdint.h`. The following sequence of commands illustrates the problem for those 3 programs:

    $ gcc *.c
    $ ./a.out
    $ echo $?
    0
    $ sed -i '1s/^/#include <stdint.h>/; s/\(nsigned \)\?long\( int\)\?\([^0-9A-Za-z_]\)/int32_t\3/g' *.c
    $ gcc -funsigned-char *.c
    $ ./a.out
    $ echo $?
    1

The easiest fix would probably be to put an explicit `signed` or `unsigned` before every `char` and to replace all `long` by `long long` (the latter is required to have a minimum width of 64 bits). I will create a pull request to fix those 3 programs in that way.

Another potential assumption might be that `int` is always at least 32 bits wide, when in fact the standard only requires it to be 16 bits wide. That might be a problem on 16-bit architectures, such as AVR for instance. It might generally make sense to use types of exact sign and width such as `int8_t`, `uint8_t`, `int64_t`, etc.

**Comment by Emoun** [comment]
This seems to have been fixed. Should be closed (I don't have permission to do this)
