### ISSUE TITLE
Parallel tools can not be compiled

### ISSUE THREAD

**Issue by albertschulz** [tacle/tacle-bench#5]
DEBIE and PapaBench can not be compiled with the "checkBenchmark.sh" script. I suppose that the script should be adjusted for those cases especially
Kind Regards

**Comment by schoeberl** [comment]
We do not yet have an agreed environment/api/model for tasks/threads needed for the parallel benchmarks. Therefore, we cannot include DEBIE and PapaBench in the execution test.

However, DEBIE and PapaBench should compile and should also be usable as WCET analysis targets.

Sorry,
Martin
