### ISSUE TITLE
How exactly should I use tacle-bench

### ISSUE THREAD

**Issue by chen116** [tacle/tacle-bench#6]
Hi,

I followed the instruction in paper and compile a couple of the benchmarks, ran them, and nothing happen.
What am I suppose to see?

I did do $git checkout V1.9

for example:
$ cd tacle-bench/bench/kernel/fft/
$ gcc -o fft fft.c fft_input.c
$./fft

And then nothing really happen. Please kindly point to me what am I doing wrong? I was expecting to see some output. Thank you!

Victor

**Comment by schoeberl** [comment]
Hi Victor,

the benchmarks are intended for WCET analysis (and any performance tests if you would like). Therefore, they just compute and do not print anything. No output at all. The should finish with an ok exit code (0).

Cheers,
Martin

**Comment by schoeberl** [comment]
The behavior observed by Victor is correct.
